name: example
description: onboarding_overlay example
publish_to: none
version: 3.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  onboarding_overlay:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/demo.gif
