name: onboarding_overlay
description: Flexible to control Onboarding overlay with or without target element (fork from onboard_overlay)
version: 2.3.1-pre.1
repository: https://github.com/talamaska/onboarding_overlay

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
