name: onboarding_overlay
description: Flexible to control Onboarding overlay with or without target element
version: 2.0.0
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
